Feature - Optimized N+1 problems and added Integration tests
wickathou/mcv-blog pull request #10
Opened 2023-11-08 10:24 UTC by wickathou

# Features
- [x] Fixed N+1 query issues on multiple views
- [x] Added new integrations tests for all the views in the app

2023-11-08 10:30 UTC, Ibizugbe reviewed
Hi @Team👋🏼👋🏼, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

It seems you have made a mistake submitting the wrong link or submitting your project in the wrong place. this is milestone on integration test and has been submitted in the `add devise` milestone. kindly do well to submit the right link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-11-08 11:49 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @wickathou  and @anshuman7negi  
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All tests are passing :heavy_check_mark: 
- Most of required asserts are present :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 11:49 UTC, tresorsawasawa commented on app/controllers/posts_controller.rb
> +    @post = Post.includes(comments: [:user]).find(params[:id])
- [ ] Good job by fixing the N+1 problem when fetching all posts and their comments without using the `bullet gem. However as required for the project, kindly ensure that your PR description includes the screenshots of your app's logs **before** and **after** the fix

2023-11-08 11:49 UTC, tresorsawasawa commented on spec/system/user_integrations_spec.rb
> +  end
- [ ] As required for the project, kindly ensure that you have a Spec file which only tests `User` index page.

- [ ] Once you have create that file, you should ensure that, it includes all the following tests:
  * Tests that asserts you can see the username of all other users.
  * Tests that asserts you can see the profile picture for each user.
  * Tests that asserts you can see the number of posts each user has written.
  * Tests that redirects to the user's show page when you click on a user.

2023-11-08 11:49 UTC, tresorsawasawa commented on spec/system/user_integrations_spec.rb
> +  end
- [ ] As required for the project, kindly ensure that you have a Spec file which only tests `User` Show page.

2023-11-08 11:49 UTC, tresorsawasawa commented on spec/system/post_integrations_spec.rb
> +  end
- [ ] As required for the project, kindly ensure that you have a Spec file which only tests `Post` index page.

2023-11-08 11:49 UTC, tresorsawasawa commented on spec/system/post_integrations_spec.rb
> +    end
- [ ] As required for the project, kindly ensure that you have a Spec file which only tests `User` ** post show page**.

2023-11-08 11:49 UTC, tresorsawasawa commented on Gemfile.lock
>  DEPENDENCIES
**README.md** file:

- [ ] To make your README looks more professional and as required the used template, kindly ensure that you update the `## Authors` section of your README by adding all authors contributors of the project

2023-11-08 14:56 UTC, codepantha requested changes
# STATUS: CHANGES REQUIRED ♻️ 

## Hi team 👋, 

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media4.giphy.com/media/rZ10JtoPRv1Ly/giphy.gif"/>

## Highlights 🎯 
✔️ Descriptive PR
✔️ All tests are passing 🟢
✔️ No linter errors

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-08 14:56 UTC, codepantha commented on spec/system/user_show_integrations_spec.rb
> +    end
- [ ] Well done for creating a `spec` file which only tests the user show page. However, for this particular test,  you need to write tests that asserts that you can see the user's first 3 posts not their last 3 posts as you have done here 👍 
![image](https://github.com/wickathou/mcv-blog/assets/46839548/cd6cf799-2c93-4ecf-898f-1a42aca8f68c)

2023-11-08 14:56 UTC, codepantha commented on spec/system/post_show_integrations_spec.rb
> +    end
- [ ] For these two tests, in order for us to truly test that the assertions are true, we need to ensure that we have at least two comments from different users. Only then can we have the rest of mind and assurance that comes with our tests passing.
![image](https://github.com/wickathou/mcv-blog/assets/46839548/10388411-322a-412f-8c97-0221e61d70bc)

2023-11-08 15:33 UTC, Ibizugbe requested changes
Hi @Team👋🏼👋🏼👋🏼, 

![request change](https://github.com/wickathou/mcv-blog/assets/64643995/bb5593a0-e76b-4b34-8149-5a1b3d0c8122)


Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights✅✅✅

- [x] The test that asserts we can see the first 3 posts has been updated👍🏼.
- [x] Linters are still passing👍🏼.


 ## Required Changes ♻️

- [ ] Nice job so far😉. Some of your test cases are still failing, kindly ensure all tests are passing before proceeding to make submissions to avoid blockers as this is a requirement that all tests should be passing😉.
<img width="751" alt="image" src="https://github.com/wickathou/mcv-blog/assets/64643995/ed25ba66-695c-4687-b8d5-6b5bf41b8717">


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 14:34 UTC, FrederickMih approved these changes
## Hi :raising_hand: @wickathou, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

:tada: :champagne: <img src="https://media.giphy.com/media/LtkRsMZNSChvICUFhV/giphy.gif"  width ="160"><img> :tada: :champagne: 

## Highlights :green_circle: 

- Tests covered all the user workflow :+1: 

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-09 15:41 UTC, merged