Feature - Validations and tests
wickathou/mcv-blog pull request #3
Opened 2023-10-26 16:41 UTC by wickathou

# Changes
- [x] Added validations to models
- [x] Added unit tests for models and methods

2023-10-26 18:33 UTC, Munsa1 commented
Hi @wickathou, kindly remove the Live Demo section from your readme file so I can review

2023-10-26 19:43 UTC, Munsa1 requested changes
Hi @wickathou, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Added All Validations :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 
Descriptive ReadMe File :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider

- [x] Consider removing the `Live Demo` section from your readme file since you have no live link to share

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-26 19:43 UTC, Munsa1 commented on spec/models/user_spec.rb
> +end
- [ ] Kindly add validation tests for the posts counter being greater than or equal to 0. I would advise the first tests to check if the post counter has a negative value to be invalid, the second if it is equal to zero to be valid and the third if it has a positive value to be valid.

2023-10-26 19:43 UTC, Munsa1 commented on spec/models/post_spec.rb
> +end
- [ ] Again kindly write tests for your validations as per the requirement.

There should be tests for:
- comments counter should be a number greater than or equal to zero
- likes counter should be a number greater than or equal to zero

2023-10-27 11:29 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @wickathou      , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some that haven't been addressed yet.
<img src="https://media2.giphy.com/media/RjQ68u1NIlcL47cCN0/giphy.gif"/>

## Highlights :fire: 
- All required user validations added :heavy_check_mark: 
- All required posts validations added :heavy_check_mark: 
- Has unit tests for  `Post`, `Comment`, 'Like' and `User` model :heavy_check_mark: 
- All tests passing :heavy_check_mark: 
- Model specs has **Validation** tests :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-27 11:29 UTC, NahnahAJ commented on spec/models/post_spec.rb
> +end
- [ ] Great job so far @wickathou There are still a few changes that need to be resolved and you'll be on your way to the next Milestone 😉 
- [ ] Just as the previous reviewer mentioned,  per the project requirements, you were asked to `Add unit specs for all of your models' methods and validations.` But currently, these validations below have still not been tested. So kindly include tests for those as well as the previous reviewer mentioned :wink: 
- [ ] There should be tests for :
- `comments counter `should be a number greater than or equal to zero
- `likes counter ` should be a number greater than or equal to zero

2023-10-27 11:29 UTC, NahnahAJ commented on app/models/user.rb
> +  validates :posts_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
- [ ] Just as the previous reviewer mentioned, Kindly ensure that you add validation tests for the `posts_count` being greater than or equal to 0. :+1: 
- [ ] Kindly ensure that your test checks that
1. When the `post counter` has a negative value, it is invalid :100: 
2. If the `post counter` is equal to zero or has a positive value, then it's valid :100:

2023-10-28 09:34 UTC, KDlamini approved these changes
### Hi @wickathou 🙋‍♀️, 

Excellent work! 💯 
You have done an outstanding job adding model validations and specs. 🎊 🥳 
Your feature is complete! There is nothing else to say other than... it's time to merge it. :shipit: 
Congratulations!!!

## Highlights 🌞
 
✔️ Good PR title and description
✔️ User and Post model validations are implemented
✔️ There are unit tests for the `User` and `Post`  models
✔️ Well-documented and professional README

## To Improve 🔧 

- **[Commit Messsages]:** It is best to write messages using present action verbs instead of past tense. For example a commit message should start with `Add` instead of `Added`.

# Status: Approved ✔️ 

![oscars-standing-ovation](https://user-images.githubusercontent.com/38088818/164766743-7f6493f3-4506-4331-9678-207bad27e7f5.gif)
 
Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-28 09:34 UTC, KDlamini commented on README.md
[OPTIONAL] README: It is always best to either remove or customize the section description since it is only meant as a instruction to the developer on how to customize each section.

![image](https://github.com/wickathou/mcv-blog/assets/38088818/1e793adb-62ec-495e-bfd7-7a624c3dd6c9)

2023-10-31 11:11 UTC, merged